TODO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('todolist.urls', 'todolist'), namespace='todolist')),
]

account/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.user_login)
]

accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.user_login),
    path('profile/', views.profile, name='profile'),
    path('tg/', views.tg_connect, name='tg')
]

todolist/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('main/', views.lobby, name='lobby'),
    path('', views.lobby),
    path('main/<int:page>', views.lobby, name='lobby_page'),
    path('<int:page>', views.lobby),
    path('create/', views.create, name='create'),
    path('mark/', views.mark, name='mark'),
    path('delete/<int:task_id>', views.delete, name='delete')
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User


class Notification(models.Model):
    date_time = models.DateTimeField()
    sent = models.BooleanField(default=False)


class Task(models.Model):
    title = models.CharField(max_length=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    done = models.BooleanField(default=False)
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE, default=None, null=True)

todolist/views.py
from django.core.paginator import Paginator, EmptyPage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Task, Notification
from django.shortcuts import render
from .tasks import notify_user
from TODO.utils import get_datetime_obj


@login_required
def lobby(request, page=1):
    tasks = Task.objects.filter(user=request.user).order_by('id').reverse().all()
    p = Paginator(tasks, 7)
    try:
        tasks = p.page(page)
    except EmptyPage:
        tasks = p.page(1)
    return render(request, 'todolist/lobby.html',
                  {'tasks': tasks.object_list, 'current_page': page, 'has_next_page': tasks.has_next(),
                   'has_prev_page': tasks.has_previous(), 'tasks_p': tasks})


@login_required
def create(request):
    response = HttpResponseRedirect(reverse('todolist:lobby'))
    if not request.method == 'POST':
        return response
    task_data = request.POST
    task = Task(user=request.user, title=task_data['title'], done=False)
    if task_data.get('date_time'):
        notification = Notification(date_time=task_data.get('date_time'))
        notification.save()
        task.notification = notification
        task.save()
        datetime = get_datetime_obj(task.notification.date_time)
        notify_user.apply_async(args=(request.user.id, task.id), eta=datetime, soft_time_limit=10, time_limit=10)
    task.save()
    return response


@login_required
def mark(request):
    redirect = HttpResponseRedirect(reverse('todolist:lobby'))
    if not request.method == 'POST':
        return redirect
    marked = dict(request.POST)
    marked.pop('csrfmiddlewaretoken')
    current = marked.pop('current_page')[0]
    if not marked:
        return redirect
    marked_ids = [int(mark_id) for mark_id in marked.keys()]
    marked_tasks = Task.objects.filter(pk__in=marked_ids)
    for marked_task in marked_tasks:
        if marked_task.done:
            marked_task.done = False
        else:
            marked_task.done = True
        marked_task.save()
    redirect['location'] += str(current)
    return redirect


@login_required
def delete(request, task_id):
    redirect = HttpResponseRedirect(reverse('todolist:lobby'))
    Task.objects.filter(pk=task_id).delete()
    return redirect

templates/todolist/lobby.html
{% extends "base.html" %}
{% block title %} Main {% endblock %}
{% block head %}
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}
{% block content %}
<section class="vh-100">
  <div class="container py-5 h-100 d-flex justify-content-center align-items-center">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-3-strong w-100 h-100" style="border-radius: 1rem;">
            <div class="card-header">
                <div class="d-flex justify-content-end">
                  <span class="fw-light fs-4 mb-0">
                       <a href="{% url 'accounts:profile' %}">{{ request.user.username }}</a>
                      <a href="{% url "accounts:logout" %}">
                      <i class="fas fa-right-from-bracket fa-1x" style="cursor: pointer"></i>
                      </a>
                  </span>
                  </div>
                <p class="fw-bold text-center fs-1 pt-0 mb-0">TODO list</p>
            </div>
          <div class="card-body p-3 h-100">
              <div class="d-flex justify-content-start mb-3" style="height: auto;">
                  <form class="w-100" method="POST" action="{% url 'todolist:create' %}">
                      <div class="input-group mb-1">
                          <div class="input-group p-0">
                              <a data-container="body" class="h-100" rel="tooltip" data-mdb-placement="left" data-mdb-toggle="tooltip" title="Set tg reminder?">
                                  <button data-mdb-toggle="collapse" data-mdb-target="#collapseExample" type="button" class="btn btn-primary h-100">
                                     <i class="fas fa-calendar"></i>
                                  </button>
                              </a>
                            <div class="form-outline">
                              <input type="text" id="id_todo" class="form-control" name="title" data-mdb-showcounter="true" maxlength="20" required/>
                              <label class="form-label" for="id_todo">To do</label>
                              <div class="form-helper"></div>
                            </div>
                          </div>
                          <button type="submit" class="btn btn-primary">
                              <i class="fas fa-plus"></i>
                          </button>
                      </div>
                      <div class="collapse mt-4" id="collapseExample">
                          {% if request.user.telegram.confirmed %}
                        <div class="form-outline mb-2" id="pickr_area">
                            <input type="text" class="form-control" id="datetimepicker"/>
                            <div class="form-helper">Set date & time</div>
                        </div>
                          {% else %}
                              <p class="fs-4 fw-light text-center">Connect <a href="{% url 'accounts:tg' %}">tg account</a> to use reminders</p>
                          {% endif %}
                      </div>
                  {% csrf_token %}
                  </form>
              </div>
              <form method="POST" action="{% url 'todolist:mark' %}">
              <div class="list-group list-group-light border ps-2 list-group-small">
                  {% for task in tasks %}
                  <li class="list-group-item d-flex justify-content-xxl-between align-items-center">
                    <input class="form-check-input" type="checkbox" name="{{ task.id }}" value="true" id="check{{ task.id }}" />
                    <label class="form-check-label {% if task.done %} text-decoration-line-through text-muted {% endif %}" for="check{{ task.id }}">{{ task.title }}
                    {% if not task.done %}
                      <span class="badge rounded-pill badge-warning">Waiting</span>
                    {% else %}
                        <span class="badge rounded-pill badge-success">Done</span>
                    {% endif %}
                      {% if task.notification and not task.notification.sent %}
                      <span class="badge rounded-pill badge-info"><i class="fas fa-clock"></i>
                          {{ task.notification.date_time }}
                      </span>
                        {% endif %}
                    {% if task.notification.sent %}
                        <span class="badge rounded-pill badge-warning">Notification sent</span>
                    {% endif %}
                  </label>
                      <a class="btn btn-rounded btn-sm btn-danger" href="{% url 'todolist:delete' task_id=task.id %}" role="button"><i class="fas fa-xmark"></i></a>
                  </li>
                  {% endfor %}
              </div>
              <div class="d-flex justify-content-center pt-2" style="height: 3rem;">
                  {% if has_prev_page %}
                  <div class="px-2 py-0">
                        <a href="{% url 'todolist:lobby_page' page=tasks_p.previous_page_number %}">
                          <button class="btn btn-link" type="button">
                            <i class="fas fa-angle-left"></i>
                          </button>
                        </a>
                  </div>
                  {% endif %}
              {% if tasks %}
                  <div class="px-2 py-0">
                      <button class="btn btn-primary btn-success"  style="background-color: #25d366;" type="submit">
                        <i class="fas fa-check"></i>
                          TOGGLE STATUS
                      </button>
                  </div>
              {% endif %}
              {% if has_next_page %}
                  <div class="px-2 py-0">
                      <a href="{% url 'todolist:lobby_page' page=tasks_p.next_page_number %}">
                          <button class="btn btn-link" type="button">
                            <i class="fas fas fa-angle-right"></i>
                          </button>
                      </a>
                  </div>
              {% endif %}
              </div>
              {% csrf_token %}
              <input name="current_page" value="{{ current_page }}" type="hidden"/>
              </form>
        </div>
      </div>
  </div>
  </div>
</section>
{% endblock %}